var tresors = [], 
    loup = {img :'loup.jpg',name:'LOUP  (BAR)',latinName:'Dicentrarchus labrax',size:'100 cm',phylum:'Vertébrés', classe:'Ostéichthyens', order:'Perciformes ', family:'Moronidae', distribution:'Méditerranée et mer Noire ; en Atlantique, de la Norvège au Sénégal.', description:'Le corps élancé, généralement gris argent, plus sombre sur le dos. Les deux nageoires dorsales sont presque jointives. Avec son corps en forme de torpille, ce redoutable prédateur est parfaitement adapté à une nage rapide, nécessaire à la capture de ses proies : poissons et céphalopodes. Les jeunes vivent souvent en bancs, alors que les adultes restent plutôt solitaires. Espèce réputée pour ses qualités gustatives et élevée en aquaculture. Les plus gros individus mesurent un mètre de long.', habitat:'Sur tous les types de fonds et dans les eaux saumâtres, jusqu’à 100 m de profondeur.'},
	dorade = {img :'dorade.jpg',name:'DAURADE ROYALE',latinName:'Sparus aurata',size:'60 cm',phylum:'Vertébrés', classe:'Ostéichthyens', order:'Perciformes ', family:'Sparidae', distribution:'Méditerranée, plus rare dans le bassin oriental et la mer Noire ; en Atlantique, des îles britanniques au cap Vert.', description:'Le corps oblong de la dorade est argenté et présente une grande tache noire soulignée de rouge au niveau de l’opercule et une bande dorée entre les deux yeux. Ses grosses lèvres dissimulent de puissantes mâchoires capables de broyer les coquilles de moules et les carapaces de crustacés. Solitaire ou vivant en petits bancs, elle peut atteindre 70 cm. D’abord mâle, ce poisson devient ensuite femelle à l’âge de 2-3 ans (hermaphrodisme protandre). Son élevage en stations aquacoles est maîtrisé.', habitat:'Prairies de posidonie, étangs littoraux, et fonds sableux jusqu’à 150 m de profondeur.Les juvéniles vivent préférentiellement dans les estuaires et les petits fonds littoraux.'},
	merou = {img :'merou.jpg',name:'MÉROU BRUN',latinName:'Epinephelus marginatus',size:'130 cm',phylum:'Vertébrés', classe:'Ostéichthyens', order:'Perciformes', family:'Serranidae', distribution:'Méditerranée sauf mer Noire ; en Atlantique, du sud des îles britanniques à l’Afrique du Sud à l’est et, à l’ouest, au sud du Brésil et en Argentine.', description:'De couleur brun-rouge, le corps de ce gros poisson (jusqu’à 1,30 m) est parsemé de taches jaunâtres et les nageoires caudales et annales sont ourlées de blanc. Cependant, selon son humeur ou son état sexuel, il peut devenir très pâle, gris avec des taches argentées ou des bandes sombres. C’est un grand prédateur qui chasse d’autres poissons, des crustacés et des céphalopodes. Il est hermaphrodite protogyne : les femelles se transforment en mâles à l’âge de 9 à 12 ans. En France, ce poisson est protégé par un moratoire d’interdiction de la pêche sous-marine et de la pêche à l’hameçon.', habitat:'Dans les failles, les éboulis et les anfractuosités des côtes rocheuses, de la surface à plus de 200 m de profondeur.'},
	mulet = {img :'mulet.jpg',name:'MULET LIPPU',latinName:'Chelon labrosus',size:'60 cm',phylum:'Vertébrés ', classe:'Ostéichthyens', order:'Perciformes', family:'Mugilidae', distribution:'Méditerranée sauf mer Noire ; Atlantique, de la Norvège au Maroc.', description:'Corps fuselé, tête massive et aplatie, museau court et obtus. Cette espèce de mulet est caractérisée par une lèvre supérieure épaisse ornée de petits tubercules. Le dos est gris bleuté, les flancs et le ventre argentés et parcourus de fines lignes longitudinales sombres. Le mulet lippu vit en banc et se nourrit d’algues, de petits invertébrés et de détritus. Il mesure 60 cm au maximum.', habitat:'Zone côtière près de la surface, près des côtes, dans les estuaires, les lagunes et les ports.'},
	chapon = {img :'chapon.jpg',name:'RASCASSE ROUGE (Chapon)',latinName:'Scorpeana Scrofa',size:'55 cm',phylum:'Vertébrés', classe:'Ostéichthyens ', order:'Scorpaeniformes ', family:'Scorpaenidae', distribution:'Méditerranée sauf mer Noire ; Atlantique, des îles Britanniques au Sénégal.', description:'Coloration variable du rouge brique au rose ou orange avec des taches foncées. Présence caractéristique de nombreux lambeaux cutanés sur la mâchoire inférieure et sur le reste du corps. Ce poisson généralement solitaire peut atteindre 50 cm. Le chapon se nourrit de poissons, crustacé et mollusques.', habitat:'Sur les fonds rocheux, parfois sur les fonds de sable, de 20 à 200 m de profondeur.'};
	tresors.push(loup, dorade, merou, mulet, chapon);



